### ISSUE TITLE
Compilation problem with 'mod_const.mod'

### ISSUE THREAD

**Issue by mariavd** [PHOTOX/ABIN#148]
Hello,

I cloned the repository on an HPC cluster and loaded the following modules:

`module load gcc/11.3.0 openmpi/4.1.4 intel-oneapi-mkl/2022.1.0`

which we usually use for compilations. 

I ran the configuration script, but `make` stops with the following error:

```
gfortran -O2 -fopenmp -fimplicit-none -Wall -Wno-integer-division -Wno-maybe-uninitialized  -c error.F90
fortran_interfaces.F90:7:8:

    7 |    use mod_const, only: DP
      |        1
Fatal Error: Cannot open module file 'mod_const.mod' for reading at (1): No such file or directory
compilation terminated.
error.F90:66:11:

   66 |       use mod_interfaces, only: finish
      |           1
Fatal Error: Cannot open module file 'mod_interfaces.mod' for reading at (1): No such file or directory
compilation terminated.
```

Do you have any suggestions how to proceed?

**Comment by danielhollas** [comment]
Hello,

Thanks for taking a look at our program and sorry for the issues.

The error is a bit confusing. Are you by any chance compiling with multiple processors? That is currently not supported. 

If that is not your issue, would you mind pasting the content of your  'make.vars' file, and providing the whole output from the compilation?

Best,

Daniel Hollas

**Comment by mariavd** [comment]
Hello,

Yes, I was running make on 4 threads. It didn't come to my mind that it could be the reason. It compiled with just `make`. I'm closing the issue. Thank you.

Best regards,
Maria

**Comment by danielhollas** [comment]
Great! I am glad that it worked.

By the way, unfurtunately there's currently not much documentation for ABIN, and the documentation is `docs/` is likely outdated. 
Feel free open an issue and ask, or feel free to email me at daniel.hollas@bristol.ac.uk.
