### ISSUE TITLE
Landau-Zener hopping scheme for multiple states

### ISSUE THREAD

**Issue by JanosJiri** [PHOTOX/ABIN#158]
The current implementation of Landau-Zener allows for hopping even between non-neighbouring states, e.g. S4 -> S0. This should be removed because the theory is not suitable for that.

**Comment by danielhollas** [comment]
@JanosJiri can you please comment on why did you close this issue?

**Comment by JanosJiri** [comment]
I created a new branch where I fixed these changes and made a pull request. So the issue raised here should be solved.
