### ISSUE TITLE
Problem with "ignore_state" not working with Baeck-An couplings

### ISSUE THREAD

**Issue by jack-t-taylor** [PHOTOX/ABIN#198]
The keyword `ignore_state` is currently not correctly functional for `couplings='baeck-an'`. 

This is a problem seen for protonated formaldimine XMS-CASPT2 FSSH/Baeck-An dynamics considering 3 states (S0, S1 and S2) within the state-averaging, but only two states (S0 and S1) in the dynamics. 

It leads to probabilities for hopping to (and populations for) S2 (i.e., state 3) being non-zero at certain points along the trajectory, which is incorrect.

As a result, most trajectories show frustrated hops when hopping to S2 is erroneously attempted. However, certain trajectories also fail with the following error reported in the `abin.out` output file:

![error_in_abin out](https://github.com/user-attachments/assets/e2e9f4fc-137c-4376-8679-251ed4143118)

As suggested by @JanosJiri, this latter problem could be due to BAGEL not calculating S2 gradients (due to the `ignore_state` keyword being partially enacted), despite ABIN wanting them as it attempts to hop to S2 at certain points along the trajectory.

**Comment by JanosJiri** [comment]
Cool, thanks for reporting it @jack-t-taylor. It should be a simple fix. I created a new PR #197 for that.
