### ISSUE TITLE
PILE tau0

### ISSUE THREAD

**Issue by suchanj** [PHOTOX/ABIN#23]
We need to set default tau0 value or warn the user if its not set. Otherwise the program runs with NaN positions.

**Comment by danielhollas** [comment]
I am confused. I think tau0 is for Nosé Hoover, but PILE termostat is based on Langevin? I don't think PILE is currently supported in ABIN, is it?

**Comment by suchanj** [comment]
Well it seems you can set inose=3 and nothing will stop you. However the default value 0.01 is only set in nosehoover.f90. For Langevin thermostat you have to set it manually - its the "centroid" inverse friction coeffcient.
Btw: I tested that with nwalk=1 the (PI)LE yields comparable results as NH and therefore could be used as an alternative stochastic thermostat.

**Comment by danielhollas** [comment]
Okay, yeah, simple Langevin for classical dynamics should work. I thought it has its own input variable, but apparently not. Still, I would introduce a separate variable, something like `tau0_langevin` to make things clearer.

Note that from my initial tests years ago, Langevin did not converge as nicely as NHC, especially for tails of the distribution, but maybe I just used a wrong parameter. Also, I have no idea whether it works correctly with PIMD or is even implemented. I don't remember from the top of my head what it takes to implement it.

**Comment by danielhollas** [comment]
I've just hit this in PR #56. I'll fix this as part of that, and also rename `tau0` to `tau0_langevin` to make it clearer.
