### ISSUE TITLE
Invalid intent for input parameters in `lz_restin`

### ISSUE THREAD

**Issue by danielhollas** [PHOTOX/ABIN#74]
I got tipped off by a compiler warning. It looks like the position and velocity arrays passed into `lz_restin` should be `intent(in)` instead of `intent(out)`. 

https://github.com/PHOTOX/ABIN/blob/4ca60042ab0f922f0202e14b42615761a2acd56b/src/landau_zener.F90#L515

Note that this is actually a bug, since variables declared as `intent(out)` are not guaranteed to have the values that you passed in, so you might be assigning random numbers here.

https://github.com/PHOTOX/ABIN/blob/4ca60042ab0f922f0202e14b42615761a2acd56b/src/landau_zener.F90#L542

I don't understand why the compiler proceeds without error here, supposedly the purpose of the `intent` attribute is to prevent such mistakes. :frowning:

**Comment by suchanj** [comment]
Good catch, I will fix this next week. I should maybe add a new test where LZ is restarted.
